group: travis_lts
env:
  global:
    TERM=dumb
language: java
jdk:
- oraclejdk8
- openjdk8
install: true
before_script:
- sudo apt udate -y || true
- sudo apt install -y --no-install-recommends curl python-pip
- sudo pip install httpie
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
script:
- bash mvnw
- bash gradlew
- bash gradlew bootRun &
- http :8080/github/search/users/dagg\?page=0\&size=2
- http :8080/github/search/users/dagge\?page=0\&size=2
- http :8080/github/search/users/daggr\?page=0\&size=2
- bash gradlew --stop || true
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
