version: "2.1"

services:

  gradle-listener-of-listener-app:
    build:
      context: ./kotlin-listeners
      dockerfile: ./gradle/Dockerfile
    volumes: ["gradle-app-data:/home/appuser"]
    networks: [backing-services]
    ports: ["8080:8080"]
    restart: unless-stopped

volumes:
  gradle-app-data: {}

networks:
  backing-services:
    driver: bridge
