version: "2.1"
services:
  redis:
    #image: redis:3.2.10
    image: healthcheck/redis:latest
    ports: ["6379:6379"]
    networks: [backing-services]
    volumes: ["redis-data:/data"]
volumes:
  redis-data: {}
networks:
  backing-services:
    driver: bridge
