version: '2.1'
services:
  #  maven-voting-app-app:
  #    build:
  #      context: .
  #      dockerfile: maven/Dockerfile
  #    volumes: ['maven-voting-app-app-data:/home/appuser']
  #    networks: [backing-services]
  #    ports: ['8080:8080']
  #    #restart: unless-stopped
  #    #mem_limit: 838860800 # 800Mb
  rabbitmq:
    build:
      context: docker
      dockerfile: Dockerfile.rabbitmq
    volumes:
    - 'rabbitmq-data:/var/lib/rabbitmq'
    - 'rabbitmq-data:/etc/rabbitmq'
    ports:
    - '5672:5672'
    - '15672:15672'
    networks: [backing-services]
volumes:
  rabbitmq-data: {}
#  maven-voting-app-app-data: {}
networks:
  backing-services:
    driver: bridge
