version: "2.1"

services:

  mongo:
    image: healthcheck/mongo:latest
    environment:
      MONGO_PORT_27017_TCP_PORT: 27017
    ports: ["27017:27017"]
    volumes: ["mongo-data:/data/db"]
    networks: [backing-services]
    restart: unless-stopped

  mongo-express:
    depends_on:
      mongo:
        condition: service_healthy
    image: mongo-express:0.42.2
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: mongo
      ME_CONFIG_BASICAUTH_PASSWORD: mongo
    ports: ["8001:8081"]
    networks: [backing-services]
    restart: unless-stopped

volumes:
  mongo-data: {}

networks:
  backing-services:
    driver: bridge
