spring:
  output:
    ansi:
      enabled: always
  mvc:
    favicon:
      enabled: false
  mustache:
    expose-request-attributes: true
    expose-spring-macro-helpers: true
management:
  endpoint:
    health:
      enabled: true
server:
  port: 8080
